### ISSUE TITLE
Could not locate the bindings file /node_modules/serialport/

### ISSUE THREAD

**Issue by scramble45** [evanshortiss/obd-parser#1]
`Could not locate the bindings file. Tried:
 → /node_code/node_modules/serialport/build/serialport.node
 → /node_code/node_modules/serialport/build/Debug/serialport.node
 → /node_code/node_modules/serialport/build/Release/serialport.node
 → /node_code/node_modules/serialport/out/Debug/serialport.node
 → /node_code/node_modules/serialport/Debug/serialport.node
 → /node_code/node_modules/serialport/out/Release/serialport.node
 → /node_code/node_modules/serialport/Release/serialport.node
 → /node_code/node_modules/serialport/build/default/serialport.node
 → /node_code/node_modules/serialport/compiled/5.8.0/linux/arm/serialport.node
    at bindings (/node_code/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/node_code/node_modules/serialport/lib/bindings.js:3:35)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/node_code/node_modules/serialport/lib/serialport.js:16:25)
    at Module._compile (module.js:413:34)
`

**Comment by scramble45** [comment]
Nevermind, serialport wasnt being installed properly due to a permissions issue. Working now.

**Comment by evanshortiss** [comment]
@scramble45 glad you got this fixed. I'm trying to work on this module in my spare time so it can be hard to get round to all the things I'd like to do. I believe their is a bug in the parsing events at the moment that might cause something to fire twice on every second "data" event. Let me know about issues and patches you might have 😄
